### ISSUE TITLE
Create temporary functions folder

### ISSUE THREAD

**Issue by athowes** [epistorm/RtEval#24]
I think for the time being while other packages are being set-up we will need a folder for shared functions which are used across this repo. Arguably we could either do:

* `functions.R`
* `functions/fct_name.R`

I think we should do the later then source all the functions. This will be easier for people to work on seperate functions without tripping over each other.

**Comment by kaitejohnson** [comment]
Would suggest we create this in an `R` folder in case we eventually want to make this a package, and agree re enforcing file_name = function_name
