### ISSUE TITLE
Generating new synthetic data partially based on real data

### ISSUE THREAD

**Issue by seabbs** [epistorm/RtEval#9]
vs. directly from purely synthetic discussions as flagged in the developer conversation: https://github.com/epiforecasts/EpiNow2/blob/main/inst/dev/recover-synthetic/rt.R

**Comment by athowes** [comment]
Is this like fit to real data and then simulate from posterior? As you mentioned during F2F conversation

**Comment by seabbs** [comment]
Yes kind of but with an additional step where you change the posterior Rt estimate for another simulated Rt trajectory (but everything else is from the posterior)
